### ISSUE TITLE
发现无法切换英文输入状态

### ISSUE THREAD

**Issue by codevampire** [fcitx/fcitx-sunpinyin#9]
在其它输入法中通常按下shift就可以成为英文输入状态，这个不行，找了一遍没找到配置开关。

**Comment by wengxt** [comment]
我测试没问题，默认配置是左 shift

以及你的 sunpinyin 是不是放在第一个了？

键盘 - XXX 应该放在第一个。

**Comment by codevampire** [comment]
是我的设置问题，Fcitx有一个额外的输入法切换键，之前不知道是干什么的。谢谢回复！
